### ISSUE TITLE
Sugestão para evitar crash de readline().

### ISSUE THREAD

**Issue by reserved1** [SarahMadalena/Inspire#2]
https://github.com/SarahMadalena/Inspire/blob/979dbda2557143ec275ba6f914ca97ff53e12aec/Sources/Inspire/main.swift#L6-L20

Quando no primeiro `readLine()` a gente só da enter, o programa não avança.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/74558455/160913037-f027557e-39aa-4357-9e07-cfd1cd5c61eb.png">

Eu reescrevi desse jeito pra tentar resolver e funciona pra esse caso: <3

<img width="524" alt="image" src="https://user-images.githubusercontent.com/74558455/160914139-a51dfbe5-e266-4ba4-8670-791f73d2e4a2.png">

**Comment by SarahMadalena** [comment]
Olá, muito obrigado!!! Eu não tinha me atentado a isso, fico muito grata pela proposta de como ajeitar para fazer funcionar sem dar erro. Se possível, gostaria muito que pudesse me explicar melhor o motivo dessa forma de reescrever funcionar para corrigir o erro da readLine() 🥰
